name: coco_dev
channels: 
    - conda-forge
    - defaults
    - anaconda
dependencies: 
    - python >= 3.9.7
    - black >= 22.3.0
    - ipython
    - jupyterlab
    - isort
    - pandas >= 1.0
    - pytest-black
    - pytest-cov
    - coveralls
    - pytest >= 5.4.3
    - pytest-datadir
    - pytest-mypy

