name: Deploy to Test PyPi

on: 
  push:
      branches:
        - release_test
jobs:
  build_and_deploy:
    name: Build the release and deploy to test pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and check packages
        run: |
          python -m build
          twine check --strict dist/*
      - name: Upload
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.GENERIC_TEST_PYPI_UPLOAD }}
          repository_url: https://test.pypi.org/legacy/

