name: build

on: ["push", "pull_request"]

jobs: 

 test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]


    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}


    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          channels: conda-forge,defaults
          mamba-version: "*"
          channel-priority: true
          activate-environment: coco-dev
          environment-file: environment.yml
          use-only-tar-bz2: true   # required for caching

    - name: Environment info
      run: | 
        mamba info
        mamba list

    - name: Switch python version
      run: |
        # mamba env create -f environment.yml 
        mamba install python=${{matrix.python-version}}
        mamba info
        mamba list

    #
    # - name: Cache pip
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    #       ${{ runner.os }}-
    #
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #
    # - name: Install package
    #   run: |
    #     pip install . -U
    #     python setup.py sdist
    #
    # - name: Print Python version and packages
    #   run: |
    #      python -c "import sys; print(sys.version)"
    #      pip list
    #
    # - name: Run tests
    #   run: |
    #      isort --project country_converter --profile black --check-only .
    #      coverage run --source=country_converter -m pytest --black -vv
    #
    # - name: Coveralls analysis
    #   run: COVERALLS_REPO_TOKEN=S31b5QjHBJmjGAj5b0IHTdyaHxRkNfO5E coveralls
